### ISSUE TITLE
mirror moz.el

### ISSUE THREAD

**Issue by monsanto** [emacsmirror/p.old#13]
Official source: https://raw.github.com/bard/mozrepl/master/chrome/content/moz.el

Also, this appears to be checked into nXhtml as well (https://github.com/emacsmirror/nxhtml/blob/master/related/moz.el), but probably shouldn't be, along with many of the other files in that folder such as visual-basic-mode.el

**Comment by monsanto** [comment]
Related: https://gist.github.com/nonsequitur/666092/raw/1ec6cea2a495c5eda0d8edd16401044d0ca85a82/moz-reload-on-save-mode.el

**Comment by tarsius** [comment]
I am mirroring https://github.com/bard/mozrepl now, but that is probably not what you were hoping for.

I could mirror just the file `moz.el` even including it's history as I have a tool for that `git-subpull`. But I have stopped importing such "partial" packages, except for packages from the emacswiki and the gnu elpa repository. `git-subpull` is a bit to fragile for non-linear history (like on the wiki) or nearly linear history (like on elpa).

Another reason why I no longer extract subtrees and/or subsets when start mirroring a new package is that I found it not to be very useful in practice. The only "partial" that I use is `mu`. I used to mirror it's `mu4e/` subdirectory as package `mu4e`. But I found that to be very cumbersome in practice and I replaced `mu4e` with the complete `mu`.

There are currently 16 (non-emacswiki/elpa) "partial" packages (remaining) on the Emacsmirror. I will probably convert some of these to "full-history including the non-elisp bits" at some point. But it's not a top priority. However I do not intend adding any more new partial packages.

Regarding the gist: please contact upstream about it.

**Comment by tarsius** [comment]
I am open to discussing this some more but for now consider this fixed.
