### ISSUE TITLE
fold-dwim is outdated

### ISSUE THREAD

**Issue by purcell** [emacsmirror/p.old#14]
I had the author fix the header and footer lines for package.el compatibility.

(He doesn't have the code available in an SCM repo, sadly: he's surprised that anyone is even still using the code...)

http://www.dur.ac.uk/p.j.heslin/Software/Emacs/Download/fold-dwim.el 
https://github.com/emacsmirror/fold-dwim/blob/master/fold-dwim.el

-Steve

**Comment by tarsius** [comment]
Thanks for letting my know. I have some import problems so I won't be able to update right away.

**Comment by tarsius** [comment]
@purcell I did not take action on this yet. So before this sends a wrong message I would like to let you know that I appreciate such reports very much.

**Comment by purcell** [comment]
@tarsius Hey, no problem. I know exactly how things can be. :-)

**Comment by tarsius** [comment]
Yeah :-) Also since Yann quietly made me a Magit contributor and then disappeared, I am quit busy dealing with the huge number of old issues and feature requests Magit has. So I wasn't able to work on the Emacsmirror much lately.

**Comment by purcell** [comment]
Well, magit's a great use of your time too. It's all good!

**Comment by tarsius** [comment]
Except, I finally had reduced my (private) list of Emacsmirror related issues to an acceptable length, only to be confronted with this: https://github.com/magit/magit/issues (see 204 for added fun).

Edit: when I started there were like 120 issues! I had it down to 60 or so and now it's exploding again.

By the way I am okay! But it is a relieve to sometimes complain about the not so pleasant parts of maintaining large archives, when someone is listening who actually knows what I am talking about :-)

**Comment by purcell** [comment]
LOL, 204 is a good one: your response was perfect. The number of `magit` issues is just a sign that the software is loved by a lot of people.

The only important thing is to make sure you're having fun along the way. :-)

**Comment by tarsius** [comment]
> LOL, 204 is a good one: your response was perfect.

Thanks. I would like to return the compliment: You always handle online discussions very professionally. And only in the good sense of "professional", not in the bend-over-trying-to-make-everyone-happy way. I admire that.

> The only important thing is to make sure you're having fun along the way. :-)

Yeah, that was the motivation for my comment on 204 :-)

**Comment by purcell** [comment]
Thanks Jonas.

**Comment by tarsius** [comment]
I have manually updated the repository.

**Comment by purcell** [comment]
Yay, thanks!
