### ISSUE TITLE
watch issue tracker instead of following org?

### ISSUE THREAD

**Issue by hurtstotouchfire** [emacsmirror/p.old#22]
Since emacsmirror is an organization, and github has worked very hard to make organizations unfollowable, should we watch the issue tracker for updates? It looks like you post here when things are added or changed in some significant way.

**Comment by tarsius** [comment]
I will setup a blog soon.

**Comment by tarsius** [comment]
> I will setup a blog soon.

Yeah well... to busy working on Magit to start blogging.

> organizations unfollowable

Anyway, I am now using a separate "user" to push to the Emacsmirror @push-emacsmirror.

Not sure if https://github.com/push-emacsmirror?tab=activity works for you. It contains everything pushed to the mirror, not just "more important events". You might get something more useful by using the github api.

**Comment by tarsius** [comment]
Hope that's enough for now.
