### ISSUE TITLE
Please mirror AUCTeX

### ISSUE THREAD

**Issue by ryanakca** [emacsmirror/p.old#3]
Please mirror AUCTeX, an integrated TeX/LaTeX environment. You can find its CVS at: http://savannah.gnu.org/cvs/?group=auctex

**Comment by tarsius** [comment]
I am mirroring the package from GNU Emacs `elpa` branch: https://github.com/emacsmirror/auctex .

I have to look into whether the cvs repository differs significantly. If it does then I will probably mirror that too.

**Comment by ryanakca** [comment]
The CVS repository differs significantly, and appears to be much more recent. CVS has twelve commits over the past week, see http://cvs.savannah.gnu.org/viewvc/auctex/ChangeLog?root=auctex&view=log , as opposed to the last commit in the elpa branch being from 3 months ago.

**Comment by tarsius** [comment]
Yes, I was a bit surprised when I just looked at it. I will try to import tomorrow.

**Comment by ryanakca** [comment]
Hi, any luck on importing AUCTeX?

**Comment by tarsius** [comment]
... I hoped I would get to it before you would have to remind me :-)
Sorry for the delay, I will get to it.

**Comment by tarsius** [comment]
So far unsuccessful.

**Comment by tarsius** [comment]
The import seems to get stuck in a loop printing these messages

```
WARNING: Invalid PatchSet 3845, Tag release_11_81:
    preview/images/prvwrk24.xpm:1.2=after, preview/ChangeLog:1.698=before. Treated as 'before'
WARNING: Invalid PatchSet 3845, Tag release_11_81:
    preview/images/prvwrk24.xpm:1.2=after, preview/images/prvwrk12.xpm:1.2=before. Treated as 'before'
WARNING: Invalid PatchSet 3845, Tag release_11_81:
    preview/images/prvwrk24.xpm:1.2=after, preview/images/prvwrk14.xpm:1.1=before. Treated as 'before'
WARNING: Invalid PatchSet 3845, Tag release_11_81:
    preview/images/prvwrk24.xpm:1.2=after, preview/images/prvwrk16.xpm:1.2=before. Treated as 'before'
WARNING: Invalid PatchSet 3845, Tag release_11_81:
    preview/images/prvwrk24.xpm:1.2=after, preview/images/prvwrk20.xpm:1.2=before. Treated as 'before'
WARNING: Invalid PatchSet 3845, Tag release_11_81:
    preview/images/prvwrk24.xpm:1.2=after, preview/images/prvwrk24.xpm:1.2=before. Treated as 'before'
WARNING: Invalid PatchSet 1261, Tag release_11_81:
    preview/images/prvwrk24.xpm:1.3=after, preview/images/prvwrk24.xbm:1.2=before. Treated as 'before'
WARNING: Invalid PatchSet 1261, Tag release_11_81:
    preview/images/prvwrk24.xpm:1.3=after, preview/images/prvwrk24.xpm:1.3=before. Treated as 'before'
WARNING: Invalid PatchSet 1265, Tag release_11_81:
    preview/images/prvwrk24.xpm:1.4=after, preview/images/prvwrk24.xpm:1.4=before. Treated as 'before'
WARNING: Invalid PatchSet 3787, Tag release_11_81:
    preview/images/prvwrk24.xpm:1.1=after, preview/images/prvwrk24.xpm:1.1=before. Treated as 'before'
```

Running cvsps uses below 10Mb and .git/objects is still empty.

Might be the reason why I am not already mirroring this. I don't know how to get the import to work and also don't want to work on that now. If you want to give it a shot yourself, this is the command I used:

```
git cvsimport -v -i -k -r origin -d :pserver:anonymous@cvs.savannah.gnu.org:/sources/auctex auctex
```

I am sorry I couldn't help you.

**Comment by ruediger** [comment]
AucTeX seems to use git now:
- http://git.savannah.gnu.org/cgit/auctex.git
- http://www.gnu.org/software/auctex/development.html

**Comment by tarsius** [comment]
Mirroring that now.
