### ISSUE TITLE
auto-dim-other-buffers has a new home

### ISSUE THREAD

**Issue by mina86** [emacsmirror/p.old#30]
Not sure how mirroring works, but auto-dim-other-buffers has a new upstream home:
https://github.com/mina86/auto-dim-other-buffers.el
Since it is already on github, perhaps it makes no sense to keep the repository on emacsmirrors as well?

Dunno… Just letting you know.

**Comment by tarsius** [comment]
Thanks for informing me. I am mirroring that now.

I haven't worked on the mirror for a few months but today, by coincidence one day after you opened this, decided that I have to finally follow these moves :-)

You are the new maintainer and this is the new official version, right?

**Comment by mina86** [comment]
On Sat, Feb 08 2014, Jonas Bernoulli notifications@github.com wrote:

> You are the new maintainer and this is the new official version, right?

Yep.
