### ISSUE TITLE
Drop CVS support

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/p.old#33]
There were only five packages left that still used CVS, four of which haven't seen a commit in half a decade.
- mulvoc, sidebrain, and versor all by John Sturdy. (The last one actually interests me.)
- mode-info

After that there was one package left which is still maintained.
- proofgeneral

However it is problematic to mirror this anyway because it is a big repository that contains much more than just the elisp. Regardless I won't support a vcs for just for one package.

Also see #31.

Edit: Turns out there is one more package w3m. The import was disabled because it no longer worked for technical reasons.

**Comment by cpitclaudel** [comment]
Hey @tarsius,

Proof General's development has now migrated to GitHub (https://github.com/ProofGeneral/PG), but google seems to be a bit slow to pick the change, and still links to https://github.com/emacsattic/proofgeneral for the query "proof general emacs".

Could we maybe change the title on the attic page to redirect to the new URL?

Cheers,
Clément.

**Comment by tarsius** [comment]
> Could we maybe change the title on the attic page to redirect to the new URL?

Done.

> https://github.com/ProofGeneral/ProofGeneral

Do you still intend to put the elisp in a separate repository as this suggests?

**Comment by cpitclaudel** [comment]
Thanks for the quick answer! Sorry I didn't express myself very clearly though.

Proof General used to be hosted on the CVS servers of the university of Edinburgh. It has recently been migrated to GitHub, on https://github.com/ProofGeneral/PG. The webpage at http://proofgeneral.inf.ed.ac.uk/ still points to the old CVS repo; it will be updated soon, as part as a larger modernization effort, but we haven't done it yet (we want to get things in a good shape before advertising the new repo).

Still, people Googling "proof general github" should find the right page, which is at https://github.com/ProofGeneral/PG . Hence the original request :)

Thanks again for the quick response!
Clément.

(reference: http://lists.inf.ed.ac.uk/pipermail/proofgeneral-devel/2015/000344.html)

**Comment by tarsius** [comment]
I changed the url, is that what you wanted me to do?
