### ISSUE TITLE
Mirror from GNU Elpa or old upstream?

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/p.old#34]
Some packages that are now part of GNU Elpa are also still available from the old upstream. Figure out whether the old repositories are still used for new development, and if not mirror from GNU Elpa instead.
- [x] f90-face f90-interface-browser https://github.com/wence-/f90-iface/issues/1
- [x] ioccur https://github.com/thierryvolpiatto/ioccur/issues/2
- [x] sokoban https://github.com/leoliu/sokoban/issues/2

**Update (20141216):**

Please help me decide whether I should mirror your repository or from the Elpa subdirectory (using `git filter-branch`). Generally I want to mirror the repository where development happens, but it most old history is lost in Elpa then I would like to avoid using that. If development happens in Elpa, do you regularly incorporate changes into your repository? Etc.

For packages not mentioned below I have already decided to mirror from GNU Elpa (but haven't done the transition yet and probably can still be convinced otherwise.

_Using separate branch_
- [x] auctex   gnu

_From subdirectory_
- [x] ada-mode        builtin
- [x] coffee-mode     github @syohex
- [x] company         github @dgutov
- [x] crisp           builtin
- [x] diff-hl         github @dgutov
- [x] eldoc-eval      github @thierryvolpiatto
- [x] undo-tree       git
- [x] wcheck-mode     github @tlikonen
- [x] websocket       github @ahyatt
- [x] yasnippet       github @capitaomorte

**Update (20141228):**
- [x] shen-mode @eschulte

**Update (20151213):**

For four packages which were previously listed above I have neither gotten any feedback nor decided on my own. I have removed those now. Many new packages were added in the meantime which are available from elpa/emacs and some other upstream. I'll probably add a similar issue for those at some later time.

**Comment by joaotavora** [comment]
@capitaomorte here on yasnippet: Depends on what you want: If you wish to track the bleeding edge, do mirror https://github.com/capitaomorte/yasnippet because that's where development is going to happen, otherwise, mirroring from GNU ELPA might soon become viable again, since I've recently learned how to do github -> ELPA.git synchs (mostly like @dgutov does). And so the ageing version in ELPA.git will soon be revived, to track at least the more stable recent features.

**Comment by tarsius** [comment]
@capitaomorte Thanks. I'll stick to your repository for the time being. The takeaway for me was that both repositories are maintained well, so it doesn't matter much to me and I just stick to the repository I'm already mirroring.

> since I've recently learned how to do github -> ELPA.git synchs (mostly like @dgutov does)

I would like to learn how you guys are doing it. Also could one of you possibly publish that somewhere, so that other packages also get synchronized properly?

**Comment by dgutov** [comment]
Development of diff-hl, company and js2-mode (not mentioned here?) all happens on GitHub.

> I would like to learn how you guys are doing it.

Basically, like this: http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/

**Comment by tarsius** [comment]
> Development of diff-hl, company and js2-mode (not mentioned here?) all happens on GitHub.

Well, I had a quick look at each repository before I posted the above list and where I was very sure that the maintainer would keep his repository in sync, I did not bother asking for his advice.

> js2-mode

That's currently mirrored from elpa. I might switch to your repository at some point, but packages migrating in that direction isn't a priority right now.

**Comment by thierryvolpiatto** [comment]
Jonas Bernoulli notifications@github.com writes:

> - thierryvolpiatto/ioccur#2 => keep

Please use the github version, I am maintaining the package there and no
more on ELPA.
Same for eldoc-eval.

Thanks.

## 

Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by syohex** [comment]
Please use [github](https://github.com/defunkt/coffee-mode) version for mirroring.
(I don't have permission to upload source code to ELPA.)

**Comment by ahyatt** [comment]
For websockets, you can continue to use github.  I usually publish to ELPA on version upgrades only.

**Comment by tlikonen** [comment]
I think **wcheck-mode** is pretty much ready and don't expect much development. Perhaps bug fixes and some minor changes. I consider my [Github repository](https://github.com/tlikonen/wcheck-mode) the primary one but my plan is to keep ELPA in sync.

**Comment by tarsius** [comment]
Thanks guys!

@thierryvolpiatto what about eldoc-eval?

**Comment by thierryvolpiatto** [comment]
Jonas Bernoulli notifications@github.com writes:

> Thanks guys!
> 
> @thierryvolpiatto what about eldoc-eval?

Same as ioccur, the ELPA version is no more maintained, I maintain only
the github versions.

## 

Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tarsius** [comment]
Thanks again @thierryvolpiatto

**Comment by eschulte** [comment]
I'm no longer maintaining shen-mode (I'm not even sure how actively shen
is used these days).  I'd go with the GNU ELPA version as if I am
pressed to provide any support I probably push it to that repo.

## 

Eric Schulte
PGP: 0x614CA05D

**Comment by tarsius** [comment]
Thanks @eschulte.
