### ISSUE TITLE
Please mirror goto-chg

### ISSUE THREAD

**Issue by sonatard** [emacsmirror/p.old#41]
EmacsWiki: Goto Chg
http://www.emacswiki.org/emacs/GotoChg

**Comment by tarsius** [comment]
`goto-last-change` is now available from https://github.com/camdez/goto-last-change.el. Take note of the readme. It might also be "fun" to read the half-dozen issues on https://github.com/milkypostman/melpa/issues which concern this.

I am currently getting the Emacsmirror back into shape. It shouldn't be that much longer until it start mirroring this package from its new upstream.

**Comment by tarsius** [comment]
Meeh, just noticed that `goto-chg` and `goto-last-change` isn't the same thing. I will have to mirror `goto-chg` again from the Emacswiki, and `goto-last-change` from Github.

**Comment by tarsius** [comment]
Both packages are being mirrored again.
