### ISSUE TITLE
add vala-mode to orphanage

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/p.old#42]
See prior discussions at milkypostman/melpa#1205 and milkypostman/melpa#1978.

---

@purcell I fully trust you to do the right thing, so you did right in not getting my prior approval to add this package. But please open an issue such as this one when creating new repositories. I didn't do that for the Emacsmirror and sometimes envy Melpa for having a fairly complete record about the considerations that went into adding packages.

**Comment by purcell** [comment]
Cool, makes sense, will do.
