### ISSUE TITLE
add vcard to orphanage

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/p.old#43]
I added vcard to the orphanage quite some time ago after I had contacted to maintainers of the various packages that bundle diverging implementations of `vcard.el`. I hopped that after I had done that step, once of them would step up and do the next step. Unfortunately that didn't work out and so I'll probably have to do it myself at one point.

@purcell Of the various packages that bundle `vcard.el` Melpa only distributes `bbdb-vcard` so Melpa users are more or less safe from these conflicts. Still I think since other packages (while not available from Melpa) do depend on `vcard.el` but not `bbdb-vcard.el` it would make sense for it to exist as a separate package and even in a repository. Maybe we can motivate @tohojo to do the merge, and then maintain it either at tojojo/vcard or emacsorphanage/vcard.

**Comment by tohojo** [comment]
> Maybe we can motivate @tohojo to do the merge, and then maintain it
> either at tojojo/vcard or emacsorphanage/vcard.

I'm not sure exactly what kind of merge you're suggesting (a cursory
glance indicates that vcard.el and bbdb-vcard.el are two entirely
separate implementations of the vcard spec?), but in any case, @vgeddes
is probably more qualified to comment. He has done quite a bit more
actual coding on bbdb-vcard than I have. :)

-Toke

**Comment by tarsius** [comment]
I am suggesting that the various forks of `vcard.el` be merged into one unified version. It should be maintained in a separate repository as a package in its own right. Then all the packages that currently bundle that library could remove their implementation.

Bundling third-party libraries is a bad idea but kinda made sense when no package manager existed yet. Bundling libraries is problematic because often upstream changes are not incorporated in a timely manner, if ever, and if multiple packages bundle the same third-party library there is the danger of these forks growing apart. This is what happened here. If two or more of these packages are installed at the same time, then it is undefined which of the `vcard.el` implementations ends up being used and as a result only one of the packages will work correctly when making use of `vcard.el`.

**Comment by tohojo** [comment]
> I am suggesting that the various forks of vcard.el be merged into one
> unified version. It should be maintained in a separate repository as a
> package in its own right. Then all the packages that currently bundle
> that library could remove their implementation.

Ah, right, got it now. Completely missed that bbdb-vcard has a bundled
version of vcard.el. Sorry about that. :)

However, I'm afraid I don't have the spare cycles to do the merge and
necessary testing of the changes. Will be happy to apply patches and/or
pull requests to make it work, but that's all I can offer, at least for
the time being, I'm afraid...

-Toke

**Comment by tarsius** [comment]
I have added the package to the orphanage a long time ago, so I am closing this now. I am not interested in merging the various forks myself, because I don't use this myself. I still hope someone does that at some point.
