### ISSUE TITLE
Mirrored packages whose github upstream has disappeared

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/p.old#44]
I am currently trying to get back on track with the Emacsmirror. Please help me figure out what has happened to your package (in case of @k-talo and @rejeep several packages) and what I should do about it.

I can (a) keep the package on the Emacsmirror, but mark it as no longer updated (b) move it to the Emacsattic, where it is also no longer updated but additionally out-of-sight, or (c) delete it without a trace.

So why did you delete the repository? Is the package no longer useful? Why? E.g. merged into something else, there is a better alternative, it was a bad idea in the first place etc. Might it still be useful to others? Etc.
- [x] ack-and-a-half        https://github.com/jhelwig/ack-and-a-half @jhelwig deleted
- [x] atomo-mode            https://github.com/citizen428/atomo-mode @citizen428 deleted
- [x] company-cmake         https://github.com/company-mode/company-cmake @dgutov deleted
- [x] double-type           https://github.com/k-talo/double-type.el @k-talo
- [x] ebot                  https://github.com/ignacy/ebot @ignacy
- [x] el-test-more          https://github.com/k-talo/el-test-more.el
- [x] fp                    https://github.com/qingl/fpdotel @qingl
- [x] groovy-mode           https://github.com/russel/Emacs-Groovy-Mode @russel
  - [x] deleted
  - [x] mirror from https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes
- [x] helm-c-moccur         https://github.com/emacs-helm/helm-c-moccur @thierryvolpiatto deleted
- [x] hippie-expand-haskell https://github.com/ispinfx/hippie-expand-haskell.el @ispinfx
- [x] hrb-mode              https://github.com/ckruse/hrb-mode @ckruse deleted
- [x] httpstatus-emacs      https://github.com/mitukiii/httpstatus-emacs @mitukiii
- [x] js2-highlight-vars    https://github.com/skiviharju/js2-highlight-vars-mode @skiviharju
- [x] mactag                https://github.com/rejeep/mactag.el @rejeep deleted
- [x] octomacs              https://github.com/jhelwig/octomacs @jhelwig
  - [x] deleted
  - [x] mirror from http://git.technosorcery.net/?p=octomacs.git;a=summary
- [x] org-wiki              https://github.com/sindikat/org-wiki @sindikat
- [x] orgml                 https://github.com/dhruvbansal/orgml @dhruvbansal deleted
- [x] package-spec          https://github.com/rejeep/package-spec deleted
- [x] package-to-carton     https://github.com/echosa/package-to-carton @echosa deleted
- [x] paste-kde             https://github.com/diogofsr/paste-kde @diogofsr
- [x] pelican-mode          https://github.com/joewreschnig/pelican-mode @joewreschnig
  - [x] deleted
  - [x] mirror from http://git.korewanetadesu.com/pelican-mode.git
- [x] pythonbrew-mini       https://github.com/franckcuny/pythonbrew-mini.el @franckcuny
- [x] pyvirtualenv          https://github.com/jorgenschaefer/pyvirtualenv @jorgenschaefer
  - [x] deleted
  - [x] instead mirror https://github.com/jorgenschaefer/pyvenv
- [x] simple-demo           https://github.com/zk-phi/simple-demo @zk-phi deleted
- [x] swank-clojure-extra   https://github.com/vu3rdd/swank-clojure-extra @vu3rdd deleted
- [x] ya-grep-edit          https://github.com/k-talo/ya-grep-edit.el

Thanks for your help!

**Comment by citizen428** [comment]
On Tue, Dec 16, 2014 at 11:59 PM, Jonas Bernoulli notifications@github.com
wrote:

> atomo-mode https://github.com/citizen428/atomo-mode @citizen428
> https://github.com/citizen428

This one can be deleted without a trace. I never properly finished it and
have no intention of doing so.

Thanks for getting in touch,
Michael

## 

Michael Kohl

http://citizen428.net | http://twitter.com/citizen428

**Comment by dgutov** [comment]
> company-cmake

It's been merged into company-mode. Thanks.

**Comment by tarsius** [comment]
@citizen428 @dgutov thanks!

**Comment by joewreschnig** [comment]
pelican-mode is now at http://git.korewanetadesu.com/pelican-mode.git because GitHub is insufferably bad. (The URL is both a website and a cloneable repository.)

Obviously since it's freely licensed you can still maintain a fork / mirror on GH if you want and that's technically possible.

**Comment by echosa** [comment]
package-to-carton can be removed. The `pallet` package does a much better job.

**Comment by russel** [comment]
On Tue, 2014-12-16 at 08:59 -0800, Jonas Bernoulli wrote:

> […]
> - groovy-mode           https://github.com/russel/Emacs-Groovy-Mode 
>   @russel

Should now be using 
https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes

[…]

## 

# Russel.

Dr Russel Winder      t: +44 20 7585 2200   voip: sip:russel.winder@ekiga.net
41 Buckmaster Road    m: +44 7770 465 077   xmpp: russel@winder.org.uk
London SW11 1EN, UK   w: www.russel.org.uk  skype: russel_winder

**Comment by russel** [comment]
I should add that there is not just a single mode in the repository, there is a grails-mode and a groovy inferior mode.

**Comment by tarsius** [comment]
@joewreschnig @echosa @russel thanks to you too!

> I should add that there is not just a single mode in the repository, there is a grails-mode and a groovy inferior mode.

I can only complete repositories and in most cases don't think it is a problem if a repository contains multiple libraries - provided they are at least loosely related and aren't bundled third-party libraries. Looks like everything is fine here.

**Comment by russel** [comment]
Grails is a Groovy Web application framework so they are intimately related :-)

**Comment by ckruse** [comment]
hrb-mode has been discontinued in favor of smartparens.

**Comment by rejeep** [comment]
You can remove `mactag.el` and `package-spec`. Both those have been deprecated.

**Comment by thierryvolpiatto** [comment]
Jonas Bernoulli notifications@github.com writes:

> - helm-c-moccur https://github.com/emacs-helm/helm-c-moccur @thierryvolpiatto

I am not the maintainer of this package.
I have removed it from emacs-helm because it was obsolete and no more
maintained.

## 

Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by zk-phi** [comment]
simple-demo is discontinued since it seemed not useful (it's not starred, and is not used even by me) and so was not updated for long time.

**Comment by jorgenschaefer** [comment]
Hello!
Pyvirtualenv got python 3 support and was renamed to pyvenv, now available
at https://github.com/jorgenschaefer/pyvenv

Jorgen

**Comment by vu3rdd** [comment]
On Tue, Dec 16, 2014 at 10:29 PM, Jonas Bernoulli notifications@github.com
wrote:

>    -
>    swank-clojure-extra https://github.com/vu3rdd/swank-clojure-extra
>    @vu3rdd https://github.com/vu3rdd
> 
> swank-clojure-extra is long deprecated. I have't touched it for years.

## 

  Ramakrishnan

**Comment by tarsius** [comment]
Thanks guys!

**Comment by jhelwig** [comment]
- ack-and-a-half https://github.com/jhelwig/ack-and-a-half @jhelwig 

I no longer maintain this. Needs a clean-room re-implementation due to license issues. 
- octomacs https://github.com/jhelwig/octomacs @jhelwig 

Moved. 
git://git.technosorcery.net/octomacs.git 
http://git.technosorcery.net/?p=octomacs.git;a=summary 
http://bugs.technosorcery.net/octomacs

**Comment by tarsius** [comment]
**To those who have not answered yet: please be a bit more specific than most of the above answers.**

Because you have removed the repository I assume that you think it's no longer useful. What I would like to know is _how much not-useful_ it is. E.g.
- This is a major-mode for a language I am no longer interested it. The elisp library also has some issues which need fixing. Obviously I have no interest in doing that myself. But if someone else wanted to write a major-mode for this language, then they would be better of basing it on my code than to start from scratch. _I would then move it to the attic, so that such a person could still retrieve the code_.
- This was a bad idea in the first place and I did know very little about elisp at the time I wrote it. Not only do I no longer use it, but someone else who wanted to do something similar would not find anything useful here, and would be better of to never look at my code. _I would then delete the package completely_.

These are the extremes, in the case of your package the truth is probably somewhere in between. So again, **please mention _why_ you did deprecate the package and whether it could still be useful to _others_.** Thanks.

**Comment by rejeep** [comment]
- `mactag.el` - No longer useful for anybody. I don't even think that anybody used it ever. At the end it didn't even work.
- `package-spec` - A predecessor to Cask.

**Comment by tarsius** [comment]
Thanks @rejeep. In the case of `package-spec` I felt comfortable just deleting it (I think the readme even mentioned Cask). But in the case of `mactag` I really had no idea, and just hoped I did not just delete the last copy of something potentially valuable.

**Comment by tarsius** [comment]
> I no longer maintain this. Needs a clean-room re-implementation due to license issues.

@jhelwig This is more useful than other answers so far, but because the answer leads to lawyer-land it opens more questions than it answers. The readme mentions `ack` and `full-ack`, which both are released under the GPL (v3+ and v2+), so if you only copied from those then you could just use GPL v3+.

I am considering to move this to the attic, but if doing so actually violates some software license, then I would have to delete it completely.

**Comment by jhelwig** [comment]
@tarsius That would require getting permission from all contributors to switch the license of their contributions.  Someone else is welcome to go through that (or do the clean-room re-implementation), as I'm afraid I have none of: the time, spoons, or desire (partially since I no longer use or maintain the project).  With the current state of things, you are best off deleting it as it does violate software licenses (which is why I mention needing a clean-room re-implementation).

**Comment by dhruvbansal** [comment]
Hi Jonas,

On Tue, Dec 16, 2014 at 10:59 AM, Jonas Bernoulli notifications@github.com
wrote:

> - orgml https://github.com/dhruvbansal/orgml @dhruvbansal
>   https://github.com/dhruvbansal
> 
> The functionality I was trying to provide with OrgML is largely present in
> OrgMode out of the box. Also, it was probably a bad idea to begin with ;).

Thanks for the good work!

-dhruv

**Comment by tarsius** [comment]
> ;; [not the GPL]
> ;;
> ;; The above copyright notice and this permission notice shall be included in all
> ;; copies or substantial portions of the Software.

@jhelwig After taking a closer look I think you are right about that, unfortunately. Deleted. Thanks.

**Comment by tarsius** [comment]
The authors of these packages did not respond and I have decided on my own that they can be removed for good:
- double-type: use key-combo instead. Strange function names
- ebot: one fairly useless macro
- el-test-more: for a package that is concerned with elisp it is to much non-standard
- fp: assorted utilities without a proper prefix
- hippie-expand-haskell: no proper prefix
- httpstatus-emacs: a single commit
- js2-highlight-vars: a single commit
- org-wiki: a single commit
- pythonbrew-mini: two commits, non-idiomatic

And finally `paste-kde` and `ya-grep-edit` were removed because they were the only ones left and I have better things to do than for upstream to respond.

**Comment by sindikat** [comment]
Sorry, I didn't realize I was mentioned here. `org-wiki` was my exercise on writing a wiki plugin for Org-mode, but I never had time to write even basic functionality, so I postponed it until unknown future. You were correct to remove it.

**Comment by tarsius** [comment]
@sindikat Thanks for the heads up.
