### ISSUE TITLE
show-point-mode v0.3 is out

### ISSUE THREAD

**Issue by wasamasa** [emacsmirror/p.old#48]
See [the discussion](https://github.com/Bruce-Connor/smart-mode-line/issues/112) and [the release](http://www.dr-qubit.org/emacs-misc/show-point-mode-0.3.el). And thanks for the work!

**Comment by tarsius** [comment]
Thanks. I am getting the file from http://www.dr-qubit.org/emacs-misc/show-point-mode.el now instead of from the wiki. I have also deleted the old version from the wiki and adjusted http://www.emacswiki.org/emacs/ShowPointMode.
