### ISSUE TITLE
sql-indent

### ISSUE THREAD

**Issue by bsvingen** [emacsmirror/p.old#49]
Is there an upstream for [sql-indent](https://github.com/emacsmirror/sql-indent)?

**Comment by tarsius** [comment]
Like for most other packages on the Emacsmirror there is a link to upstream at the top of the respective Github page. Unfortunately in this case upstream publishes on the Emacswiki. You might want to contact Matt Henry <mcthenry+gnu@gmail.com> and ask him to move to Github or something similar.

**Comment by bsvingen** [comment]
In agreement with Matt I am moving this to GitHub.

Could you please update the upstream link to point to [bsvingen/sql-indent](https://github.com/bsvingen/sql-indent)? (Or, better yet, just fork that repo?)

Thank you.

**Comment by tarsius** [comment]
Thanks. I am mirroring that now.

**Comment by bsvingen** [comment]
Thank you.

(Seems to be "ident", though, not "indent"?)
