### ISSUE TITLE
http://emacsmirror.org splash page is disabled

### ISSUE THREAD

**Issue by brontitall** [emacsmirror/p.old#50]
The splash page at [http://emacsmirror.org](http://emacsmirror.org) is disabled by GitHub. Displays the following message:

> Oh no! It looks like this Pages site has been disabled due to a misconfigured custom domain.
> 
> Are you the site owner? You can quickly fix this issue by updating the DNS record for your Pages site:
> 
> If you're using a subdomain (coolthing.example.com, www.example.com, etc.), make sure you have a CNAME record that points to your-username.github.io.
> If you're not using a subdomain (example.com), make sure you have two A records set to the following IPs: 192.30.252.153 and 192.30.252.154

... but instead, the DNS looks like this:

```
;; ANSWER SECTION:
emacsmirror.org.    6943    IN  A   204.232.175.78
```

**Comment by tarsius** [comment]
Yeah ... I figured I would not update until I have a little more to show. But right now I am busy getting Magit 2.1.0 ready.

**Comment by brontitall** [comment]
Fair enough. I’d certainly favour a new version of Magit :)

**Comment by tarsius** [comment]
Okay fixed it. Wasn't much work, I just really really hate the network "solutions" webpage. There are always two ways to do perform a given task there. Click on "Pay only $XX to do XY" or search the documentation and then click through ten pages.
