### ISSUE TITLE
help-key's upstream repository has disappeared

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/p.old#51]
`help-key`s repository used to be located at https://github.com/m2ym/help-key-el. It no longer is.

@m2ym What happened to it? Is it obsolete? Or was it moved elsewhere?

**Comment by m2ym** [comment]
I've deleted the repository because I felt nobody used it.

**Comment by tarsius** [comment]
Okay, thanks for the information. I have removed this from the mirror.
