### ISSUE TITLE
Moving emacs-easy-budget and eredis to github

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/p.old#53]
Google Code is shutting down, see http://google-opensource.blogspot.ch/2015/03/farewell-to-google-code.html.

@justinhj Could you please consider moving emacs-easy-budget and eredis from to Github. There are buttons on https://code.google.com/p/emacs-easy-budget and https://code.google.com/p/eredis which allows you to easily do so.

**Comment by justinhj** [comment]
Will do at some point. I have tried twice and in the first attempt it failed after about 12 hours. In the second attempt the service was too busy to even begin the process.

**Comment by tarsius** [comment]
No hurry. And thanks.

**Comment by tarsius** [comment]
Maybe you could give this another try now?

**Comment by tarsius** [comment]
(Note to self: packages were removed because symbols are not properly prefixed.)
