### ISSUE TITLE
Moving packages away from Google Code

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/p.old#57]
Google Code is shutting down, see http://google-opensource.blogspot.ch/2015/03/farewell-to-google-code.html.
### svn
- [x] #52 epm-mode (removed)
- [x] #53 emacs-easy-budget and eredis (removed)
- [x] #54 jdibug
### hg

Contacted the authors by mail.
- [x] furl
- [x] nav
- [x] soap-client

**Comment by tarsius** [comment]
@nex3 Please consider moving your package to github. All you have to do is to go to https://code.google.com/p/furl-el/ and click on "Export to GitHub". But please also let me know once you have done that.

**Comment by nex3** [comment]
@tarsius I did it a while ago: https://github.com/nex3/furl-el

**Comment by tarsius** [comment]
Thanks @nex3, I am mirroring that now.
