### ISSUE TITLE
Moving packages away from Gitorious

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/p.old#58]
Sadly Gitorious is shutting down, see https://about.gitlab.com/2015/03/03/gitlab-acquires-gitorious.

The following packages still have to be migrated elsewhere:
- [x] delicious (frozen)
- [x] evil (but see #60)
- [x] latex-math-preview (frozen)
- [x] notmuch-unread (frozen)
- [x] pov-mode
- [x] symbols-mode
- [x] tempbuf (frozen)

**Comment by tarsius** [comment]
Please consider migrating your package to github (or gitlab or bitbucket, or host it yourself).
- @johnsu01 delicious
- @ytaka latex-math-preview
- @davexunit notmuch-unread
- @melmothx pov-mode
- @rev22 tempbuf

**Comment by tarsius** [comment]
@johnsu01 @ytaka @davexunit @melmothx @rev22 ping

**Comment by tarsius** [comment]
I have _frozen_ these packages, i.e. I no longer attempt to update them, which wouldn't work anyway since gitorious is no more. Once a maintainer informs me where he has move his package, then I will start mirroring from there.

**Comment by melmothx** [comment]
Jonas Bernoulli notifications@github.com writes:

> I have frozen these packages, i.e. I no longer attempt to update them,
> which wouldn't work anyway since gitorious is no more. Once a
> maintainer informs me where he has move his package, then I will start
> mirroring from there.

Here we go:

git@github.com:melmothx/pov-mode.git

## 

Marco

**Comment by davexunit** [comment]
I need some time to relocate my repo.  It's one of the repos I forgot to move when Gitorious shut down.

**Comment by tarsius** [comment]
@melmothx Thanks, mirroring that now.
@davexunit No hurry, just let me know when it's done.
