### ISSUE TITLE
Dropping bzr support 

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/p.old#61]
Bazzar is effectively dead and as far as I know nobody uses it for new packages. There are only very few packages remaining that are still in bzr repositories and most of them seem to be stale.
### on launchpad
- [x] mediawiki
- [x] menu-tree (removed)
- [x] nxhtml
- [x] pgrok
- [x] python-mode
- [x] records (frozen)
- [x] text-translator (removed)
- [x] thing-at-point-utils (removed)
- [x] vm (frozen)
- [x] weblogger (removed)
- [x] winring
- [x] xml-rpc
### elsewhere
- [x] dvc (frozen)

---

I will add removed packages again and resume updating frozen packages once they have been moved away from bzr (and if necessary fixed up a bit). Of course maintainers are under no obligation to do that (but if you do, then please inform me). Likewise I don't have to keep supporting bzr for just a handful of packages.

**Comment by tarsius** [comment]
@hexmode You have already migrated mediawiki and xml-rpc. But not weblogger. Is the latter obsolete?

**Comment by tarsius** [comment]
Please consider moving your package to Github.
- @iRi-E menu-tree
- @juri pgrok
- @khiker text-translator
- @warsaw winring
- @andreas-roehler python-mode and thing-at-point-utils

**Comment by warsaw** [comment]
I'll be moving winring to git soon and @andreas-roehler and I have been talking about moving python-mode.el to git also.  Note that Launchpad supports git now, although I've moved most of my stuff to GitLab.  Launchpad is free software (AGPL), and GitLab has an open source edition (MIT) so I prefer it over GitHub for my own stuff.

**Comment by warsaw** [comment]
One other comment, and a question: I have no problem with GitHub mirrors of my projects.  After I convert winring to git, where ever I host it, is there anything you need me to do?

**Comment by tarsius** [comment]
> is there anything you need me to do?

Just let me know where you moved the packages to. Thanks!

**Comment by warsaw** [comment]
https://gitlab.com/warsaw/winring

Thanks!

**Comment by tarsius** [comment]
I get a 404 with that.

**Comment by warsaw** [comment]
Oh darn.  I think GitLab now creates private projects by default.  I've flipped it to public; please try again!

**Comment by hexmode** [comment]
I haven't updated weblogger in a while, but I do want to use it every once in a while.  If I get a tuit, I'll move it to git when I work on it.

**Comment by juri** [comment]
Yeah, pgrok is as stale as they come. I migrated it anyway, and it's now at https://github.com/juri/pgrok.

**Comment by tarsius** [comment]
Thanks!

**Comment by andreas-roehler** [comment]
Hi Jonas,

thing-at-point-utils is delivered by

https://github.com/andreas-roehler/werkstatt.git

Is this okay?

Thanks,

Andreas

Am 04.08.2015 um 18:16 schrieb Jonas Bernoulli:

**Comment by tarsius** [comment]
@andreas-roehler it looks a bit messy, and the name "werkstatt" implies that this is a sort of "all of my elisp in one place" repository. It would probably be better to split this up into several repositories. Or are all libraries related to the thing-at-point?

I'll mirror this as-is, provided all libraries originate in this repository. You are not bundling any third-party libraries, are you?

**Comment by andreas-roehler** [comment]
Am 05.08.2015 um 19:54 schrieb Jonas Bernoulli:

> @andreas-roehler https://github.com/andreas-roehler it looks a bit 
> messy,

Right. Will look how  to split it into appropriate repos.

**Comment by andreas-roehler** [comment]
Am 05.08.2015 um 19:54 schrieb Jonas Bernoulli:

> @andreas-roehler https://github.com/andreas-roehler it looks a bit 
> messy,

Reordering the repo. Will signal when ready,

thanks,

Andreas

**Comment by andreas-roehler** [comment]
Am 05.08.2015 um 19:54 schrieb Jonas Bernoulli:

> @andreas-roehler https://github.com/andreas-roehler it looks a bit 
> messy, and the name "werkstatt" implies that this is a sort of "all of 
> my elisp in one place" repository.

Reorganized the repo into
- subroutines
- thing-at-point-utils
- sh-werk
- general-key

and
- misc

Beside "misc" directories are accessible as single repos from

https://github.com/andreas-roehler?tab=repositories

**Comment by tarsius** [comment]
Thanks. Will do something about this as soon as my flatmate pays the cable bill...

**Comment by tarsius** [comment]
@andreas-roehler Thanks for your efforts. But I have decided to not mirror these packages for the time being - there are still to many symbols that lack a proper prefix.

Should I mirror pythong-mode from https://gitlab.com/python-mode-devs/python-mode now?

**Comment by andreas-roehler** [comment]
Am 14.08.2015 um 13:26 schrieb Jonas Bernoulli:

> @andreas-roehler https://github.com/andreas-roehler Thanks for your 
> efforts. But I have decided to not mirror these packages for the time 
> being - there are still to many symbols that lack a proper prefix.

Okay, will look for that.

> Should I mirror pythong-mode from 
> https://gitlab.com/python-mode-devs/python-mode now?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/emacsmirror/p/issues/61#issuecomment-131082309.

IMO yes, thanks.
