### ISSUE TITLE
Adding oo-browser to emacsattic

### ISSUE THREAD

**Issue by Wilfred** [emacsmirror/p.old#63]
Hi @tarsius 

I'd like to add http://sourceforge.net/projects/oo-browser/ to the emacsattic. It's a cute project that hasn't been updated since 2002.

What do I need in order to make this happen? As far as I can see it's just a zip available on sourceforge.

**Comment by tarsius** [comment]
Do you have some interest in reviving it? If so, then I would rather add it to the orphanage.

https://github.com/emacsorphanage

**Comment by Wilfred** [comment]
I may patch it so it works on modern Emacsen, but I'm not interested in maintaining it.

**Comment by tarsius** [comment]
I've created the repository and given you access. Please import and maybe do the patching. Please use the actual author as the GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL, and use an GIT_AUTHOR_DATE which matches the date when the release tarball was created.

**Comment by tarsius** [comment]
I just noticed that `oo-browser` already is available from the attic! I'll look into that - you might not have to do a manual import.

**Comment by tarsius** [comment]
I'll leave it at that. If you do modernize it, then please open a pr. I will then merge that, move it to the orphanage, and then mirror that repository again.
