### ISSUE TITLE
Packages which Emacsmirror imports from file and Melpa imports from Emacsmirror

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/p.old#67]
- [x] diminish
- [ ] edit-list
- [ ] escreen
- [ ] fm
- [ ] fold-dwim
- [ ] hl-sexp @hober
- [ ] ldap-mode @loveshack
- [ ] mpg123
- [ ] mwe-log-commands
- [ ] osx-plist @hober
- [ ] psvn
- [ ] quack
- [ ] revive
- [ ] vkill
- [ ] x-dict
- [ ] xterm-frobs
- [ ] xterm-title

To those maintainers who have an account on Github: please consider making each of your packages available as a separate repository. Thanks!

**Comment by loveshack** [comment]
I don't know what Emacsmirror is, but anyway I'm not going to change my
revision control, especially in response to a request out of the blue.

**Comment by myrjola** [comment]
@tarsius I have taken over maintainership of diminish after a private mail conversation with the original author Will Mengarini. The official repository is now https://github.com/myrjola/diminish.el. I will soon open a pull request to MELPA to target that repository instead of Emacsmirror. Thank you for mirroring diminish.el all these years!

**Comment by tarsius** [comment]
@myrjola Thanks a lot!

**Comment by tarsius** [comment]
@myrjola I'm always looking for people who would like to breath life back into an old package which is still used by many. Let me know if you need any new projects :-)

**Comment by tarsius** [comment]
@loveshack That's fine.

It sounds like you are using some version control system. Is there a public repository somewhere? If so then Melpa could build the packages from that instead of getting them from the Emacsmirror.

Melpa can create packages for libraries that are made available by the respective upstream using either a git, hg, darcs, bzr, cvs, svn, or fossil repository or by putting it on Emacswiki. Melpa gets some packages which are not available like this by instead treating the repository on the Emacsmirror as the "upstream repository".

These repositories are updated very irregularly by downloading the plain file from the real upstream and then committing it using a generic commit message. It is problematic that Melpa uses these repositories because they are only updated very irregularly.

They are updated irregularly because the majority of the packages which are not yet available from some vc repository and are still updated occasionally, are very few. As a result Melpa's packages for these few active projects can be out of date. If you would like to prevent that for your packages, then you should make them available using a version control system of your choice.
