### ISSUE TITLE
Mirror from GNU Elpa or Github

### ISSUE THREAD

**Issue by tarsius** [emacsmirror/p.old#69]
For many packages available from Elpa there also exist a repository on Github. If the Github repository is actively maintained, then I prefer to mirror that. From the maintainers of the following repositories I would like to know:
## 
1. Should your package be mirrored from Github? Why (not)?
2. Where does development happen primarily?
3. How are the repositories synced?
4. How often do you sync?
5. Do commits flow in both directions?
## 
- [x] [company-math](https://github.com/vspinu/company-math) @vspinu
- [x] [dts-mode](https://github.com/bgamari/dts-mode) @bgamari
- [x] [electric-spacing](https://github.com/xwl/electric-spacing) @xwl
- [x] [loc-changes](https://github.com/rocky/emacs-loc-changes) @rocky
- [x] [math-symbol-lists](https://github.com/vspinu/math-symbol-lists) @vspinu
- [x] [minimap](https://github.com/dustinlacewell/emacs-minimap) @dustinlacewell
- [x] [on-screen](https://github.com/michael-heerdegen/on-screen.el) @michael-heerdegen
- [x] [test-simple](https://github.com/rocky/emacs-test-simple) @rocky
## 

Except for `minimap`, I now mirror the versions from Github.

**Comment by rocky** [comment]
1. Yes
2. Github
3. manually
4. rarely
5. Generally not, but it could

**Comment by ghost** [comment]
Hello Jonas,

> - on-screen @michael-heerdegen

That's me.

> 1 Should your package be mirrored from Github? Why (not)? 

That's the homepage.  I guess it's more or less the same, since the two
places (Gnu Elpa and Github) will be in sync 99% of the time.

> 2 Where does development happen primarily? 

There is not much development currently, the thing has arrived it's
final state.  Further development will happen at github.

> 3 How are the repositories synced?

In Gnu Elpa, it's a subtree that I manually sync from the github server.

> 4 How often do you sync?

I didn't need to until now.  I plan to sync after every single change.

> 5 Do commits flow in both directions?

Unlikely, but not totally impossible (sometimes, people change your
stuff at Gnu Elpa without even telling you).

HTH, Michael.

**Comment by bgamari** [comment]
1. Yes
2. Github
3. Manually
4. No need to thusfar
5. Generally not.

**Comment by rocky** [comment]
@tarsius this is going to be annoying getting replies from all package owners. If you want a response from me in the future, don't communicate via an issue with several parties. 

I do not nor ever have derived benefit from this mirror. If you want to remove my packages from this mirror please do so if it will mean I don't have to be bothered with stuff like this in the future. Thanks.

**Comment by tarsius** [comment]
@rocky Okay. I'll try to remember that in the future.

You might want to click on the **Unsubscribe** button in the rightmost column.

Ps: You might have benefited from my work on the Emacsmirror without knowing it. I regularly compare with Melpa and in the process I often end up fixing issues in Melpa. I also have fixed issues in hundreds of packages and submitted these fixes upstream.

**Comment by xwl** [comment]
1. Yes
2. Github
3. Manually
4. Rarely
5. Generally not.

**Comment by tarsius** [comment]
Thanks for the quick replies!

**Comment by vspinu** [comment]
HI @tarsius. Same as with others: 
1. Yes
2. Github
3. Manually
4. Rarely
5. Generally not.

**Comment by tarsius** [comment]
Thanks @vspinu.

**Comment by tarsius** [comment]
That leaves `minimap`. Upon closer inspection it turns out these are actually two different implementations. When there is a name conflict between a built-in/elpa package and a third-party package, then I always go with the official one.
