### ISSUE TITLE
emacsmirror/perltidy out of date

### ISSUE THREAD

**Issue by matthewpersico** [emacsmirror/p.old#71]
Latest version (0.05) is here: https://www.emacswiki.org/emacs/perltidy.el

**Comment by tarsius** [comment]
I haven't been mirroring from the wiki very often recently. But I did so a few days ago, so this should be up-to-date now.

I recommend that users of packages that are still hosted on the wiki, kindly ask the maintainers to move with the times and switch to git or hg.
