### ISSUE TITLE
dict.el is out of date

### ISSUE THREAD

**Issue by rrthomas** [emacsmirror/p.old#9]
I uploaded a newer version to the Emacs Wiki, with fixes from the Debian package and the Debian BTS (the fixes are not Debian-specific).

http://www.emacswiki.org/emacs/dict.el

**Comment by tarsius** [comment]
It's not just out of date - it's a different implementation. The one on the Emacsmirror is very old so I should probably switch to the one used by Debian. I remember having tried (or at least having considered) to import the Debian emacs-goodies-el. I will look into this again but cannot do so right now. Ping me again if there is no progress for two weeks or so.

You could help by
1. pointing me to the source tarball (not deb), if that even is available
2. figuring out whether there is an upstream for all of emacs-goodies-el or parts thereof

If there aren't any individual upstream(s) that provides unpackaged sources then I likely won't be able to mirror the packages contained in emacs-goodies-el individually. I might then mirror emacs-goodies-el but only if it does not bundle libraries that are already mirrored separately on the Emacsmirror (except dict.el).

I might end up mirroring the dict.el that you have extracted from the goodies. But in that case I would prefer if you made it available as a git repository and explicitly committed to maintaining it. Have you send your changes to the Debian maintainers, or intend to do so?

**Comment by rrthomas** [comment]
On 11 April 2013 15:18, Jonas Bernoulli notifications@github.com wrote:

> It's not just out of date - it's a different implementation.
> 
> I'm sorry, I hadn't noticed.
> 
> The one on the Emacsmirror is very old so I should probably switch to the
> one used by Debian. I remember having tried (or at least having considered)
> to import the Debian emacs-goodies-el. I will look into this again but
> cannot do so right now. Ping me again if there is no progress for two weeks
> or so.
> 
> I don't think this is a good idea. emacs-goodies-el has been a useful
> stop-gap while there was no Emacs packaging system, but now there are such
> systems we should be using those.
> 
> You could help by
> 1. pointing me to the source tarball (not deb), if that even is
>    available
> 
> As for all Debian packages, you can find that from the package page:

http://packages.debian.org/sid/emacs-goodies-el

> 1. figuring out whether there is an upstream for all of
>    emacs-goodies-el or parts thereof
> 
> Details will be in the package. Certainly, the package itself (from which
> the tarball comes) is Debian-specific.
> 
> If there aren't any individual upstream(s) that provides unpackaged
> sources then I likely won't be able to mirror the packages contained in
> emacs-goodies-el individually. I might then mirror emacs-goodies-el but
> only if it does not bundle libraries that are already mirrored separately
> on the Emacsmirror (except dict.el).
> 
> As I say, I don't think that's a good idea. emacs-goodies-el should be
> returned to its various upstreams.
> 
> I might end up mirroring the dict.el that you have extracted from the
> goodies. But in that case I would prefer if you made it available as a git
> repository and explicitly committed to maintaining it. Have you send your
> changes to the Debian maintainers, or intend to do so?
> 
> Yes, I gave the bug number. However, I make no commitment to maintain it
> (which is why I uploaded it to EmacsWiki), as it is effectively superceded
> by dictionary.el:

http://www.myrkr.in-berlin.de/dictionary/

although that itself needs some fixes which are in its Debian package,
dictionary-el:

http://packages.debian.org/search?keywords=dictionary-el

## 

http://rrt.sc3d.org

**Comment by tarsius** [comment]
I have removed the old `dict` from the mirror. Unfortunately I cannot mirror the implementation from the wiki yet, because of major problems with the wiki importer (see #26).

Ps: Is there any hope debian will split up their goodies?

**Comment by rrthomas** [comment]
I think the idea with emacs-goodies-el is not that it will be split up, but rather gradually retired in favour of other (non-Debian) packaging systems; but as with most things in Debian, I am unsure when (or whether) this will actually happen.
